public with sharing class HelloMoon {
    public void say1() {
        System.debug('1');
    }
    public void say2() {
        System.debug('2');
    }

    public void say3() {
        System.debug('3');
    }

    public void say4() {
        System.debug('4');
    }

    public void say5() {
        System.debug('5');
    }

    public void say6() {
        System.debug('6');
    }

    public void say7() {
        System.debug('7');
    }

    public void say8() {
        System.debug('8');
    }

    public void say9() {
        System.debug('9');
    }

    public void say10() {
        System.debug('10');
    }
     
     public void manav(Account b, Account b1,Account b2,Account b3,Account b4,Account b5,Account b6,Account b7, Account b99){
        //public static Account setAccountName(Account b){
        if (b.Description != null){
            b.name= 'Account name -demo';
        }}
}